language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
script:
  - pep8 storytracker
  - pyflakes storytracker
  - coverage run test.py
after_success:
  - coveralls
