language: python
python:
  - "2.7"
install:
  - pip install pyflakes pep8 coverage python-coveralls
  - sudo apt-get install phantomjs
  - python setup.py install
  - export PYTHONPATH="$PYTHONPATH:`pwd`"
script:
  - pep8 storytracker
  - pyflakes storytracker
  - coverage run test.py
after_success:
  - coveralls
